#!/usr/bin/env python

import gettext, sys, os

gettext.bindtextdomain(os.environ['TEXTDOMAIN'], os.environ['TEXTDOMAINDIR'])
gettext.textdomain(os.environ['TEXTDOMAIN'])

print gettext.gettext(' '.join(sys.argv[1:])),
