/**
 * Pages configuration
 */

global.pages = [
	//EN
	{ language: 'en-us', route: '/',                      view: 'index',      destination: '/index_en.html',                                                            urls: { en: '/index_en.html',         pt: '/' }, title: 'Getup Cloud | Scalable Cloud Application | Grow in the cloud', keywords: 'Cloud, getup, getup cloud, host sites', description: 'Getup is a scalable cloud application plataform' },
	{ language: 'en-us', route: '/technology',            view: 'technology', destination: '/technology/index.html',            partial: 'technologies/en/',            urls: { en: '/technology',            pt: '/tecnologia' }, title: 'Getup Cloud | Scalable Cloud Application | Grow in the cloud', keywords: 'Cloud, getup, getup cloud, host sites', description: 'Getup is a scalable cloud application plataform' },
	{ language: 'en-us', route: '/technology/php',        view: 'technology', destination: '/technology/php/index.html',        partial: 'technologies/en/php/',        urls: { en: '/technology/php',        pt: '/tecnologia/php' }, title: 'Getup PHP Hosting | See how it works', keywords: 'Host PHP, Cakephp, Symfony, CodeIgniter', description: 'PHP Developer - Getup is a simple way to get your PHP application in the cloud.'  },
	{ language: 'en-us', route: '/technology/ruby',       view: 'technology', destination: '/technology/ruby/index.html',       partial: 'technologies/en/ruby/',       urls: { en: '/technology/ruby',       pt: '/tecnologia/ruby' }, title: 'Getup Ruby Hosting | See how it works', keywords: 'Host Ruby, Ruby on Rails, Sinatra, Rails', description: 'Ruby Developer - Getup is a simple way to get your Ruby application in the cloud.'  },
	{ language: 'en-us', route: '/technology/nodejs',     view: 'technology', destination: '/technology/nodejs/index.html',     partial: 'technologies/en/nodejs/',     urls: { en: '/technology/nodejs',     pt: '/tecnologia/nodejs' }, title: 'Getup Node.js Hosting | See how it works', keywords: 'Host Node.js, JavaScript, Express, Stylus', description: 'Node.js Developer - Getup is a simple way to get your Node.js application in the cloud.'  },
	{ language: 'en-us', route: '/technology/python',     view: 'technology', destination: '/technology/python/index.html',     partial: 'technologies/en/python/',     urls: { en: '/technology/python',     pt: '/tecnologia/python' }, title: 'Getup Python Hosting | See how it works', keywords: 'Host Python, Django, WSGI', description: 'Python Developer - Getup is a simple way to get your Python application in the cloud.'  },
	{ language: 'en-us', route: '/technology/java',       view: 'technology', destination: '/technology/java/index.html',       partial: 'technologies/en/java/',       urls: { en: '/technology/java',       pt: '/tecnologia/java' }, title: 'Getup Java Hosting | See how it works', keywords: 'Host Java, JBoss, Tomcat, Spring, Scala/Play, Liferay', description: 'Java Developer - Getup is a simple way to get your Java application in the cloud.'  },
	{ language: 'en-us', route: '/technology/perl',       view: 'technology', destination: '/technology/perl/index.html',       partial: 'technologies/en/perl/',       urls: { en: '/technology/perl',       pt: '/tecnologia/perl' }, title: 'Getup Perl Hosting | See how it works', keywords: 'Host Perl, Aplicação Perl', description: 'Perl Developer - Getup is a simple way to get your Perl application in the cloud.'  },
	{ language: 'en-us', route: '/technology/mysql',      view: 'technology', destination: '/technology/mysql/index.html',      partial: 'technologies/en/mysql/',      urls: { en: '/technology/mysql',      pt: '/tecnologia/mysql' }, title: 'Getup MySQL | See how it works', keywords: 'MySQL, PHPMyAdmin', description: 'MySQL Developer - Getup is a simple way to get your MySQL application in the cloud.'  },
	{ language: 'en-us', route: '/technology/postgresql', view: 'technology', destination: '/technology/postgresql/index.html', partial: 'technologies/en/postgresql/', urls: { en: '/technology/postgresql', pt: '/tecnologia/postgresql' }, title: 'Getup PostgreSQL | See how it works', keywords: 'PostgreSQL ', description: 'PostgreSQL Developer - Getup is a simple way to get your PostgreSQL application in the cloud.'  },
	{ language: 'en-us', route: '/technology/mongodb',    view: 'technology', destination: '/technology/mongodb/index.html',    partial: 'technologies/en/mongodb/',    urls: { en: '/technology/mongodb',    pt: '/tecnologia/mongodb' }, title: 'Getup MongoDB | See how it works', keywords: 'NoSQL, JSON, MongoDB', description: 'MongoDB Developer - Getup is a simple way to get your MongoDB application in the cloud.'  },
	//PT
	{ language: 'pt-br', route: '/',                      view: 'index',      destination: '/index.html',                                                               urls: { en: '/index_en.html',         pt: '/' }, title: 'Getup Cloud | Hospedagem na nuvem | Grow in the cloud', keywords: 'Cloud, getup, getup cloud, nuvem, hospedagem sites', description: 'Getup é uma plataforma para hospedagem na nuvem' },
	{ language: 'pt-br', route: '/technology',            view: 'technology', destination: '/tecnologia/index.html',            partial: 'technologies/pt/',            urls: { en: '/technology',            pt: '/tecnologia' }, title: 'Getup Cloud | Hospedagem na nuvem | Grow in the cloud', keywords: 'Cloud, getup, getup cloud, nuvem, hospedagem sites', description: 'Getup é uma plataforma para hospedagem na nuvem'  },
	{ language: 'pt-br', route: '/technology/php',        view: 'technology', destination: '/tecnologia/php/index.html',        partial: 'technologies/pt/php/',        urls: { en: '/technology/php',        pt: '/tecnologia/php' }, title: 'Hospedagem PHP Getup | Saiba como funciona', keywords: 'Hospedagem PHP, Cakephp, Symfony, CodeIgniter', description: 'Hospedagem PHP - A Getup oferece uma forma simples de hospedar suas aplicações PHP na nuvem. Conheça nossa hospedagem PHP.'  },
	{ language: 'pt-br', route: '/technology/ruby',       view: 'technology', destination: '/tecnologia/ruby/index.html',       partial: 'technologies/pt/ruby/',       urls: { en: '/technology/ruby',       pt: '/tecnologia/ruby' }, title: 'Hospedagem Ruby on Rails  Getup | Saiba como funciona', keywords: 'Hospedagem Ruby on Rails', description: 'Hospedagem Ruby on Rails - A Getup oferece uma forma simples de hospedar suas aplicações Ruby on Rails na nuvem. Conheça nossa hospedagem Ruby on Rails.'  },
	{ language: 'pt-br', route: '/technology/nodejs',     view: 'technology', destination: '/tecnologia/nodejs/index.html',     partial: 'technologies/pt/nodejs/',     urls: { en: '/technology/nodejs',     pt: '/tecnologia/nodejs' }, title: 'Hospedagem Node.js Getup | Saiba como funciona', keywords: 'Hospedagem Node.js, JavaScript, Express, Stylus', description: 'Hospedagem Node.js - A Getup oferece uma forma simples de hospedar suas aplicações Node.js na nuvem. Conheça nossa hospedagem Node.js.'  },
	{ language: 'pt-br', route: '/technology/python',     view: 'technology', destination: '/tecnologia/python/index.html',     partial: 'technologies/pt/python/',     urls: { en: '/technology/python',     pt: '/tecnologia/python' }, title: 'Hospedagem Python Getup | Saiba como funciona', keywords: 'Hospedagem Python, Django, WSGI', description: 'Hospedagem Python - A Getup oferece uma forma simples de hospedar suas aplicações Python na nuvem. Conheça nossa hospedagem Python.'  },
	{ language: 'pt-br', route: '/technology/java',       view: 'technology', destination: '/tecnologia/java/index.html',       partial: 'technologies/pt/java/',       urls: { en: '/technology/java',       pt: '/tecnologia/java' }, title: 'Hospedagem Java Getup | Saiba como funciona', keywords: 'Hospedagem Java, JBoss, Tomcat, Spring, Scala/Play, Liferay', description: 'Hospedagem Java - A Getup oferece uma forma simples de hospedar suas aplicações Java na nuvem. Conheça nossa hospedagem Java.'  },
	{ language: 'pt-br', route: '/technology/perl',       view: 'technology', destination: '/tecnologia/perl/index.html',       partial: 'technologies/pt/perl/',       urls: { en: '/technology/perl',       pt: '/tecnologia/perl' }, title: 'Hospedagem Perl Getup | Saiba como funciona', keywords: 'Hospedagem Perl, Aplicação Perl', description: 'Hospedagem Perl - A Getup oferece uma forma simples de hospedar suas aplicações Perl na nuvem. Conheça nossa hospedagem Perl.'  },
	{ language: 'pt-br', route: '/technology/mysql',      view: 'technology', destination: '/tecnologia/mysql/index.html',      partial: 'technologies/pt/mysql/',      urls: { en: '/technology/mysql',      pt: '/tecnologia/mysql' }, title: 'MySQL Getup | Saiba como funciona', keywords: 'Hospedagem MySQL, PHPMyAdmin', description: 'Hospedagem MySQL - A Getup oferece uma forma simples de hospedar suas aplicações MySQL na nuvem. Conheça nossa hospedagem MySQL.'  },
	{ language: 'pt-br', route: '/technology/postgresql', view: 'technology', destination: '/tecnologia/postgresql/index.html', partial: 'technologies/pt/postgresql/', urls: { en: '/technology/postgresql', pt: '/tecnologia/postgresql' }, title: 'PostgreSQL Getup | Saiba como funciona', keywords: 'Hospedagem PostgreSQL', description: 'Hospedagem PostgreSQL - A Getup oferece uma forma simples de hospedar suas aplicações PostgreSQL na nuvem. Conheça nossa hospedagem PostgreSQL.'  },
	{ language: 'pt-br', route: '/technology/mongodb',    view: 'technology', destination: '/tecnologia/mongodb/index.html',    partial: 'technologies/pt/mongodb/',    urls: { en: '/technology/mongodb',    pt: '/tecnologia/mongodb' }, title: 'MongoDB Getup | Saiba como funciona', keywords: 'NoSQL, JSON, Hospedagem MongoDB', description: 'Hospedagem MongoDB - A Getup oferece uma forma simples de hospedar suas aplicações MongoDB na nuvem. Conheça nossa hospedagem MongoDB.'  },
];